typography_spectrum: 0.7643263338220371
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.43870218592474586
  lightness: 0.8061830443002763
  saturation: 0.6200518966364758
  rhythmicContrast: 0.4972995656870748
github: true
layout_spectrum: 0.9079058195132357
analytics:
  facebook: ''
author:
  name: Moemen Fouad
  url: 'http://projectized.co'
  email: moemen@projectized.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
name: Creek General Transport
url: 'https://thegrid.ai/creek/'
navigation:
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: 'Gallery '
    id: 41eab09d-d285-418c-9878-2251fee67833
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
title: When you care enough to send the very best
content: []
description: Transport Solutions & Services
purpose:
  - type: contact
    label: Contact Now!
    url: 'mailto:info@creek-transportation.com'
