layout_spectrum: 0.24705806296180455
typography_spectrum: 0.40982067722246274
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.8794165954102605
  lightness: 0.9415025360781772
  saturation: 0.2726411907148022
  rhythmicContrast: 0.6018944181040814
name: Creek Transport
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
analytics:
  facebook: ''
  google: UA-90536695-1
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Email Us
    url: 'mailto:info@creek-transport.com'
  - type: contact
    label: Call Now!
    url: 'tel:00971502758333'
title: When you care enough to send the very best
description: Transport Solutions & Services
author:
  name: Projectized.co
  url: 'http://projectized.co'
  email: moemen@projectized.co
content_rating:
  adult: false
navigation:
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Why GC Transport?
    id: 46276743-3ca0-4bae-a93d-8fecea1c9804
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: Our Policies
    id: cc2a6386-b102-42c5-b814-df74f625df50
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ae8e4aa-0e18-4820-b187-c2bfdfb51c19.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ae8e4aa-0e18-4820-b187-c2bfdfb51c19.png
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      keywords: []
      publisher:
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
