name: Creek General Transport
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
layout_spectrum: 0.90597305529714
typography_spectrum: 0.22478752034873065
analytics:
  facebook: '1715905985406141'
  google: UA-90536695-1
  twitter: ''
opengraph:
  type: Pixel
  appId: '1715905985406141'
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.2087456261983492
  lightness: 0.9774703524184256
  saturation: 0.9261846444991851
  rhythmicContrast: 0.6790982873029638
purpose:
  - type: contact
    label: Call Now!
    url: 'tel:00971502758333'
  - type: contact
    label: Email Us
    url: 'mailto:info@creektransport.com'
title: When you care enough to send the very best
description: Transport Solutions & Services
author:
  name: Moemen Fouad
  url: 'http://projectized.co'
  email: moemen@projectized.co
content_rating:
  adult: false
navigation:
  - name: Why GC Transport?
    id: 46276743-3ca0-4bae-a93d-8fecea1c9804
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: Our Policies
    id: cc2a6386-b102-42c5-b814-df74f625df50
    type: content
  - name: Our Customers
    id: d551d80c-0774-4148-b2ae-6a61d18160f6
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/creekgeneral.transport.1'
    type: external
  - name: Twitter
    url: 'https://twitter.com/creek_transport'
    type: external
  - name: LinkedIn
    url: 'https://ae.linkedin.com/in/creekgeneral-transport-42917b137'
    type: external
content: []
github: true
