layout_spectrum: 0.6935701650125665
typography_spectrum: 0.40843358670573426
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.9442001485506459
  lightness: 0.7466417526306197
  saturation: 0.8611034784469717
  rhythmicContrast: 0.6948694429748534
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics:
  facebook: ''
author:
  name: Projectized.co
  url: 'http://projectized.co'
  email: moemen@projectized.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
name: Creek General Transport
url: 'http://creektransport.com'
navigation:
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Why GC Transport?
    id: 46276743-3ca0-4bae-a93d-8fecea1c9804
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: Our Policies
    id: cc2a6386-b102-42c5-b814-df74f625df50
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
title: When you care enough to send the very best
content: []
description: Transport Solutions & Services
purpose:
  - type: contact
    label: Contact Now!
    url: 'mailto:info@creek-transport.com'
  - type: contact
    label: Call Now!
    url: 'tel:00971502758333'
