layout_spectrum: 0.14255154081767812
typography_spectrum: 0.18866557129354464
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.14125641340048672
  lightness: 0.9197081964618831
  saturation: 0.9230817967069584
  rhythmicContrast: 0.05193650695025036
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics:
  facebook: ''
author:
  name: Projectized.co
  url: 'http://projectized.co'
  email: moemen@projectized.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
name: Creek General Transport
navigation:
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Why GC Transport?
    id: 46276743-3ca0-4bae-a93d-8fecea1c9804
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: 'Gallery '
    id: 41eab09d-d285-418c-9878-2251fee67833
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
title: When you care enough to send the very best
content: []
description: Transport Solutions & Services
purpose:
  - type: contact
    label: Contact Now!
    url: 'mailto:info@creek-transport.com'
  - type: contact
    label: Call Us
    url: 'tel:00971502758333'
