layout_spectrum: 0.90597305529714
typography_spectrum: 0.22478752034873065
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.2087456261983492
  lightness: 0.9774703524184256
  saturation: 0.9261846444991851
  rhythmicContrast: 0.6790982873029638
name: Creek General Transport
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
analytics:
  facebook: '1715905985406141'
  google: UA-90536695-1
  twitter: ''
opengraph:
  type: Pixel
  appId: '1715905985406141'
purpose:
  - type: contact
    label: Call Now!
    url: 'tel:00971502758333'
  - type: contact
    label: Email Us
    url: 'mailto:info@creektransport.com'
title: When you care enough to send the very best
description: Transport Solutions & Services
author:
  name: Projectized.co
  url: 'http://projectized.co'
  email: moemen@projectized.co
content_rating:
  adult: false
navigation:
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: Our Policies
    id: cc2a6386-b102-42c5-b814-df74f625df50
    type: content
  - name: Our Customers
    id: d551d80c-0774-4148-b2ae-6a61d18160f6
    type: content
  - name: Contact Us
    id: b0ffd366-b54a-4fb0-b58b-be09631f0ee0
    type: content
  - name: Facebook
    url: 'https://www.facebook.com/creekgeneral.transport.1'
    type: external
  - name: Twitter
    url: 'https://twitter.com/creek_transport'
    type: external
  - name: LinkedIn
    url: 'https://ae.linkedin.com/in/creekgeneral-transport-42917b137'
    type: external
  - name: Why GC Transport?
    id: 46276743-3ca0-4bae-a93d-8fecea1c9804
    type: content
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FI_xiFzoh55o%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DI_xiFzoh55o&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FI_xiFzoh55o%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Moemen Fouad
          url: 'https://www.youtube.com/user/lickyslicky'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - duration
        - views
        - transport
        - wdtvlive42
        - railroad
        - tbjimcollins
        - s88tv1
        - trains
        - newshour
        - archive
      description: Creek General Transport - Fleet Slide Show
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=I_xiFzoh55o'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=I_xiFzoh55o
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=I_xiFzoh55o
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/I_xiFzoh55o'
      title: Creek General Transport
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FI_xiFzoh55o%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DI_xiFzoh55o&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FI_xiFzoh55o%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Moemen Fouad
          url: 'https://www.youtube.com/user/lickyslicky'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - duration
        - views
        - transport
        - wdtvlive42
        - railroad
        - tbjimcollins
        - s88tv1
        - trains
        - newshour
        - archive
      description: Creek General Transport - Fleet Slide Show
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=I_xiFzoh55o&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=I_xiFzoh55o'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=I_xiFzoh55o
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=I_xiFzoh55o
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/I_xiFzoh55o'
      title: Creek General Transport
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
