layout_spectrum: 0.5669919214883616
typography_spectrum: 0.8530721274785475
color:
  brandColors:
    - '#80BA27'
    - '#E30917'
    - '#C3DF9B'
    - '#7C7A7B'
    - '#F58A93'
  brandStrength: 0.5036104643869554
  lightness: 0.8211866041205564
  saturation: 0.9864470887317848
  rhythmicContrast: 0.984071368395563
github: true
author:
  name: Moemen Fouad
  url: 'http://projectized.co'
  email: moemen@projectized.co
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/554dd206-1efe-471f-815d-b90684e6bee5.png
name: Creek General Transport
navigation:
  - name: About Us
    id: 19aa20fb-9edd-4c4c-8092-ea385ac8be16
    type: content
  - name: 'Mission, Vision & Values'
    id: 68e90db3-95b1-454c-8cba-272e98329b69
    type: content
  - name: Services
    id: d55961db-d434-45b9-9d9e-81478ebc1e75
    type: content
  - name: 'Fleet Gallery '
    id: 8cbc138d-9781-4ba2-9a37-686e5b8effb2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1206424e-4977-4f51-86b9-46f9ec5f0d4a.png
title: When you care enough to send the very best
content: []
description: Transport Solutions & Services
purpose:
  - type: contact
    label: Contact Now!
    url: 'mailto:info@creek-transportation.com'
